import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Amplify } from "aws-amplify";
import config from "../aws-exports";
import Nav from "./components/nav";

Amplify.configure(config, { ssr: true });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-blog-blue"}>
        <Nav />
        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
