/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://kw32go7dlrchzhlgoyulw4tbnu.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3eqp3e24fbgkhnfhowupgetjbm",
    "aws_cognito_identity_pool_id": "eu-west-2:ad9e7b88-e262-4c72-8a61-a1a4bacedfd6",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_scfrUsp49",
    "aws_user_pools_web_client_id": "7sh4bued8hjve2g5tgk4t9f0i3",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "blogsite737fe794961a4d84968528aded199002202619-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
